require: rubocop-rails

AllCops:
  Exclude: 
    - "test/**/*" 
    - "config/**/*" 
    - "db/**/*"
    - "bin/**/*"
    - "config.ru"
    - "Gemfile"
    - "Rakefile"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
    Enabled: false